#!/bin/sh
# shellcheck disable=SC3043

bold=$(tput bold)
normal=$(tput sgr0)

# Load nvm if available
if [ -s "$HOME/.nvm/nvm.sh" ]; then
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\\n" "$text" >> "$zshrc"
    else
      printf "\\n%s\\n" "$text" >> "$zshrc"
    fi
  fi
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

# Determine Homebrew prefix
arch="$(uname -m)"
if [ "$arch" = "arm64" ]; then
  HOMEBREW_PREFIX="/opt/homebrew"
else
  HOMEBREW_PREFIX="/usr/local"
fi

if ! command -v brew >/dev/null; then
  fancy_echo "------ Installing ${bold}Homebrew${normal} ------"
    /bin/bash -c \
      "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    append_to_zshrc "eval \"\$($HOMEBREW_PREFIX/bin/brew shellenv)\""

    export PATH="$HOMEBREW_PREFIX/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "------ Uninstalling old Homebrew-Cask ------"
  brew uninstall --force brew-cask
fi

fancy_echo "------ Updating ${bold}Homebrew${normal} formulae ------"
brew update --force # https://github.com/Homebrew/brew/issues/1151

csv_file="program_list.csv"

# Read and process the CSV file
tail -n +2 "$csv_file" | while IFS="," read -r appname appcommand cask customsearch; do
  # Determine the search command based on customsearch
  search_command=""
  if [ -n "$customsearch" ]; then
    search_command="$customsearch"
  else
    search_command="command -v $appname"
  fi

  # Check if the app is installed
  if ! eval "$search_command" &> /dev/null; then
    fancy_echo "------ Installing ${bold}$appname${normal} ------"
    
    # Install the app using Homebrew
    if [ "$cask" = "true" ]; then
      brew install --cask "$appcommand"
      fancy_echo "------ Installed ${bold}$appname${normal} ------"
    else
      brew install "$appcommand"
      fancy_echo "------ Installed ${bold}$appname${normal} ------"
    fi
  else
    fancy_echo "------ ${bold}$appname${normal} is already installed ------"
  fi
done

fancy_echo "------ Install ${bold}Node v16.15.1${normal} ------"
nvm install 16.15.1
fancy_echo "------ Install ${bold}Node v16.14.0${normal} ------"
nvm install 16.14.0
fancy_echo "------ Install ${bold}Node v14.20.0${normal} ------"
nvm install 14.20.0
fancy_echo "------ Install ${bold}Yarn${normal} ------"
sudo npm i -g yarn

declare -a apps=(
    '/System/Applications/Utilities/Terminal.app'
    '/Applications/Google Chrome.app'
    '/Applications/Visual Studio Code.app'
    '/Applications/MySQLWorkbench.app'
    '/Applications/OpenVPN Connect.app'
    '/Applications/Postman.app'
    '/Applications/Slack.app'
);

function add_app_to_dock {
    app="${1}"

    if open -Ra "${app}"; then
        fancy_echo "${bold}$app${normal} added to the Dock"

        defaults write com.apple.dock persistent-apps -array-add "<dict>
                <key>tile-data</key>
                <dict>
                    <key>file-data</key>
                    <dict>
                        <key>_CFURLString</key>
                        <string>${app}</string>
                        <key>_CFURLStringType</key>
                        <integer>0</integer>
                    </dict>
                </dict>
            </dict>"
    else
        echo "ERROR: Application ${bold}$1${normal} not found."
    fi
}

declare -a links=(
    'https://www.gripinvest.in'
    'http://3.109.36.87/'
    'https://app.datadoghq.com/apm/home'
    'https://github.com/gripinvest'
    'https://gripinvest.atlassian.net/jira/software/c/projects/PT/boards/2'
);

function open_link_in_chrome {
    link="${1}"
    open -a /Applications/Google\ Chrome.app/ $link
}

fancy_echo "Laptop setup complete"

echo "Do you want add the installed apps to Dock? (Y/N)"
read add_to_dock

if [ "$add_to_dock" = "Y" ]; then
  fancy_echo "${bold}Adding install applications to Dock${normal}"
  for app in "${apps[@]}"; do
    add_app_to_dock "$app"
  done
  fancy_echo "${bold}Restarting the Dock..${normal}"
  killall Dock
elif [ "$add_to_dock" = "N" ]; then
  fancy_echo "Ok! Not adding to dock"
else
  fancy_echo "Invalid input. Skipping the step..."
fi

echo "Do you want me to open important links on Google Chrome so that you can add them as bookmark? (Y/N)"
read add_bookmark

if [ "$add_bookmark" = "Y" ]; then
  fancy_echo "${bold}Opening links on Chrome${normal}"
  for link in "${links[@]}"; do
    open_link_in_chrome "$link"
  done
elif [ "$add_bookmark" = "N" ]; then
  fancy_echo "Laptop onboarding complete. Exiting now..."
else
  fancy_echo "Invalid input. Exiting now..."
fi